const meta = {
  "index": "Diagnostics",
  "common-codes": "Common Codes: 30FF, Misfires & More",
  "misfire": "Misfire",
  "rough-idle": "Rough Idle",
  "long-crank": "Long Crank",
  "no-start": "No Start",
  "low-boost": "Low Boost",
  "overboost": "Overboost",
  "boost-oscillation": "Boost Oscillation",
  "wastegate-rattle": "Wastegate Rattle (Diagnosis)",
  "timing-corrections": "Timing Corrections (Diagnosis)",
  "lean-condition": "Lean Condition",
  "rich-condition": "Rich Condition",
  "fuel-pressure-crash": "Fuel Pressure Crash",
  "hpfp-failure": "HPFP Failure",
  "lpfp-failure": "LPFP Failure",
  "injector-failure": "Injector Failure",
  "coil-failure": "Coil Failure",
  "spark-plug-issues": "Spark Plug Issues",
  "vanos-codes": "VANOS Codes",
  "throttle-closures": "Throttle Closures (Diagnosis)",
  "limp-mode": "Limp Mode",
  "30ff-underboost": "30FF Underboost",
  "29dc-fuel-pressure": "29DC Fuel Pressure",
  "2aaf-fuel-pump-plausibility": "2AAF Fuel Pump Plausibility",
  "2abc-3100-boost-faults": "2ABC / 3100 Boost Faults",
}

export default meta
