const meta = {
  index: {
    title: 'Home',
    display: 'hidden',
  },
  'start-here': 'Start Here',
  sep_kb: {
    type: 'separator',
    title: 'N54 Knowledge Base',
  },
  'n54-overview': 'N54 Overview',
  models: 'Models',
  dme: 'DME / ROM',
  fuel: 'Fuel',
  boost: 'Boost',
  ignition: 'Ignition',
  'load-torque': 'Load / Torque',
  vanos: 'VANOS',
  'cooling-oil': 'Cooling / Oil',
  maintenance: 'Maintenance',
  diagnostics: 'Diagnostics',
  logging: 'Logging',
  maps: 'Maps',
  'build-paths': 'Build Paths',
  parts: 'Parts',
  media: 'Media',
  sep_school: {
    type: 'separator',
    title: 'Tuning School',
  },
  engine: 'Engine',
  tuning: 'Tuning Stages',
  hardware: 'Hardware',
  fueling: 'Fueling',
  datalogging: 'Datalogging',
  lessons: 'Tuning Lessons',
  'map-reference': 'Map Reference',
  'workflow-guides': 'Workflow Guides',
  'log-diagnostics': 'Log Diagnostics',
  checklist: 'Checklists',
  synergy: {
    title: 'Synergy BMW Tuning',
  },
}

export default meta
